projects:
  digitaldashappwebapp:
    schemaPath: amplify/backend/api/digitaldashappwebapp/build/schema.graphql
    includes:
      - aws/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: aws/graphql
        region: us-west-2
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
