/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:3db1b112-bf78-487d-8fdb-e3ba53034e7a",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_FgSEWYy2P",
    "aws_user_pools_web_client_id": "st9d2l0ob5ust5ls67csvncjt",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "FAMILY_NAME",
        "GIVEN_NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://zkuit3kdonbv5hqbs25lnolefy.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-l6vduekqpncarbpled5mmiecmm",
    "aws_user_files_s3_bucket": "digitaldashappwebappf75b1782aa4043dda5c63d5b46b162021-staging",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
