service: update-analytics
provider:
  name: aws
  stage: ${opt:stage, 'staging'}
  region: us-west-2
  profile: milan
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - sqs:SendMessage
          Resource: arn:aws:sqs:us-west-2:125288872271:update-analytics-queue-${self:provider.stage}
        - Effect: Allow
          Action:
            - dynamodb:Scan
          Resource: arn:aws:dynamodb:us-west-2:125288872271:table/Profile-${self:custom.appsync_api_id.${opt:stage, self:provider.stage}}-${self:provider.stage}
  environment:
    ENV: ${self:provider.stage}
    APPSYNC_API_ID: ${self:custom.appsync_api_id.${opt:stage, self:provider.stage}}

functions:
  updateAnalytics:
    handler: src/index.handler
    events:
      - eventBridge:
          schedule: cron(0 * * * ? *)
custom:
  appsync_api_id:
    staging: 7hdw3dtfmbhhbmqwm7qi7fgbki
    prod: b7rvoho6bjf3xcicxkq6ivubgy
  